---
title: "Installation des packages"
output: 
  github_document:
    toc: true
    toc_depth: 2
---

``` {bash}
sudo apt-get update -y 
sudo apt-get install -y libglpk-dev
```

En suivant les instructions sur https://benjjneb.github.io/dada2/dada-installation.html

# Installation de BiocManager et dada2

```{r package install}
if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install(version = '3.11')
BiocManager::install("dada2", version = "3.11")
```

# Installation de phyloseq

```{r}
BiocManager::install("phyloseq")
```

# Installation de phangorn

```{r}
BiocManager::install("phangorn")
```

# Installation de Decipher

```{r}
BiocManager::install("DECIPHER")
```

# Installation de gridExtra

```{r}
install.packages("gridExtra")
```

# Installation de ggplot2

```{r}
install.packages('ggplot2')
```

# Autres installations

```{r}
library("knitr")
library("BiocManager")
.cran_packages <- c("ggplot2", "gridExtra")
.bioc_packages <- c("dada2", "phyloseq", "DECIPHER", "phangorn")
.inst <- .cran_packages %in% installed.packages()
if(any(!.inst)) {
   install.packages(.cran_packages[!.inst])
}
.inst <- .bioc_packages %in% installed.packages()
if(any(!.inst)) {
   source("http://bioconductor.org/biocLite.R")
   BiocManager::install(.bioc_packages[!.inst], ask = F)
}
# Load packages into session, and print package version
sapply(c(.cran_packages, .bioc_packages), require, character.only = TRUE)
```

```{r}
.cran_packages <- c( "shiny","miniUI", "caret", "pls", "e1071", "ggplot2", "randomForest", "dplyr", "ggrepel", "nlme", "devtools",
"reshape2", "PMA", "structSSI", "ade4",
"ggnetwork", "intergraph", "scales")
.github_packages <- c("jfukuyama/phyloseqGraphTest")
.bioc_packages <- c("genefilter", "impute")
# Install CRAN packages (if not already installed)
.inst <- .cran_packages %in% installed.packages()
if (any(!.inst)){
    install.packages(.cran_packages[!.inst],repos = "http://cran.rstudio.com/")
}
.inst <- .github_packages %in% installed.packages()
if (any(!.inst)){
    devtools::install_github(.github_packages[!.inst])
}

.inst <- .bioc_packages %in% installed.packages()
if(any(!.inst)){
    Biocmanager::install(.bioc_packages[!.inst])
}

```

# Installation de DeSeq2

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("DESeq2")
```

# Installation de StructSSI et usethis

```{bash}
wget https://cran.r-project.org/src/contrib/Archive/structSSI/structSSI_1.1.1.tar.gz
```

```{r}
install.packages("usethis")
```

```{r}
library(devtools)
install_local("./structSSI_1.1.1.tar.gz")
```

# Installation de ade4 et factoextra

```{r}
install.packages("ade4") # Calcul de l'ACP
install.packages("factoextra")# Visualisation de l'ACP
```

# Installation de RMarkdown

```{r}
install.packages("rmarkdown")
```




















